#ifndef FIRMWARE_INCLUDE_SYSTEM_TYPES_H
#define FIRMWARE_INCLUDE_SYSTEM_TYPES_H

#include <stdbool.h>
#include <stdint.h>

typedef enum {
    SYSTEM_STATE_NORMAL = 0,
    SYSTEM_STATE_DEGRADED,
    SYSTEM_STATE_SAFE_OFF,
    SYSTEM_STATE_EMERGENCY
} system_state_t;

typedef uint32_t alm_category_mask_t;
typedef uint32_t reset_reason_t;

typedef enum {
    TIME_SOURCE_UNKNOWN = 0,
    TIME_SOURCE_RTC_DS3231
} time_source_t;

typedef enum {
    SAFEOFF_REASON_NONE = 0,
    SAFEOFF_REASON_THERMAL_CRITICAL,
    SAFEOFF_REASON_ATO_OVERFLOW,
    SAFEOFF_REASON_ELECTRIC_TOTAL,
    SAFEOFF_REASON_PLUG_SHORT,
    SAFEOFF_REASON_MCP23017_FAIL,
    SAFEOFF_REASON_CONFIG_INVALID,
    SAFEOFF_REASON_SELFTEST_FAIL,
    SAFEOFF_REASON_FSM_INVALID,
    SAFEOFF_REASON_WDT_RECOVERY,
    SAFEOFF_REASON_MANUAL_CRITICAL,
    SAFEOFF_REASON_OVERVOLTAGE,
    SAFEOFF_REASON_UNDERVOLTAGE,
    SAFEOFF_REASON_THERMAL_EXTREME
} safeoff_reason_t;

typedef enum {
    ERR_AUTH_REQUIRED = 0,
    ERR_AUTH_INVALID,
    ERR_AUTH_FORBIDDEN,
    ERR_STATE_NOT_ALLOWED,
    ERR_PLUG_BLOCKED,
    ERR_VALIDATION_ERROR,
    ERR_CONFIG_INVALID,
    ERR_SCHEMA_INCOMPATIBLE,
    ERR_STORAGE_UNAVAILABLE,
    ERR_HARDWARE_UNAVAILABLE,
    ERR_SAFE_MODE_ACTIVE,
    ERR_MONITOR_ONLY_ACTIVE,
    ERR_RATE_LIMITED,
    ERR_INTERNAL_ERROR
} canonical_error_code_t;

#endif
