/* @requirement RF-HW-PIN-001 a RF-HW-PIN-046 / RNF-HARDWARE-001
 * TC-PINMAP-001: pin_map.h contém as macros normativas (AF.3 / GO CODING RevA). */
#include "unity.h"
#include "pin_map.h"

TEST_CASE("TC-PINMAP-001 macros normativas presentes e corretas", "[pinmap]")
{
    /* GPIO normativos canônicos. */
    TEST_ASSERT_EQUAL_INT(4,  PIN_DS18B20_1WIRE_GPIO);
    TEST_ASSERT_EQUAL_INT(17, PIN_PZEM_UART_TX_GPIO);
    TEST_ASSERT_EQUAL_INT(18, PIN_PZEM_UART_RX_GPIO);
    TEST_ASSERT_EQUAL_INT(8,  PIN_I2C_SDA_GPIO);
    TEST_ASSERT_EQUAL_INT(9,  PIN_I2C_SCL_GPIO);
    TEST_ASSERT_EQUAL_INT(11, PIN_SPI_MOSI_GPIO);
    TEST_ASSERT_EQUAL_INT(12, PIN_SPI_MISO_GPIO);
    TEST_ASSERT_EQUAL_INT(13, PIN_SPI_SCK_GPIO);
    TEST_ASSERT_EQUAL_INT(5,  PIN_RELAY_P01_GPIO);
    TEST_ASSERT_EQUAL_INT(6,  PIN_RELAY_P02_GPIO);
    TEST_ASSERT_EQUAL_INT(10, PIN_TFT_CS_GPIO);
    TEST_ASSERT_EQUAL_INT(16, PIN_TFT_DC_GPIO);
    TEST_ASSERT_EQUAL_INT(21, PIN_TFT_RST_GPIO);
    TEST_ASSERT_EQUAL_INT(47, PIN_TFT_BL_GPIO);
    TEST_ASSERT_EQUAL_INT(38, PIN_TOUCH_CS_GPIO);
    TEST_ASSERT_EQUAL_INT(39, PIN_TOUCH_IRQ_GPIO);
    TEST_ASSERT_EQUAL_INT(15, PIN_SD_CS_GPIO);
    TEST_ASSERT_EQUAL_INT(41, PIN_ADC1_CS_GPIO);
    TEST_ASSERT_EQUAL_INT(42, PIN_ADC2_CS_GPIO);

    /* Expansor MCP23017 e mapa de canais ADC. */
    TEST_ASSERT_EQUAL_HEX8(0x20, MCP23017_I2C_ADDR);
    TEST_ASSERT_EQUAL_INT(0, MCP23017_P03_BIT);
    TEST_ASSERT_EQUAL_INT(7, MCP23017_P10_BIT);
    TEST_ASSERT_EQUAL_INT(3, ADC2_CH_AD_KEYPAD);
    TEST_ASSERT_EQUAL_INT(2, ADC2_CH_ATO_LEVEL);

    /* Pino não utilizado sentinela. */
    TEST_ASSERT_EQUAL_INT(-1, PIN_UNUSED);
}
