// @requirement RF-UI-INPUT-001 Eventos de HMI desacoplados
#pragma once

#include <stdint.h>

typedef enum {
    UI_EVENT_NONE = 0,
    UI_EVENT_REQUEST_FEED_MODE,
    UI_EVENT_REQUEST_EXIT_FEED_MODE,
    UI_EVENT_REQUEST_ACK_ALERT,
    UI_EVENT_REQUEST_MUTE,
    UI_EVENT_REQUEST_SAVE_THERMAL_CONFIG,
    UI_EVENT_REQUEST_PLUG_ACTION,
    UI_EVENT_REQUEST_SAFE_REBOOT,
    UI_EVENT_REQUEST_FACTORY_RESET,
    UI_EVENT_NAVIGATE_HOME,
    UI_EVENT_NAVIGATE_BACK
} ui_event_t;

void ui_events_emit(ui_event_t event);
